exports.trees = [
  {
    name: "Ponderosa Pine",
    scientific_name: "Pinus Ponderosa",
    max_height: 262,
    leaf: "Evergreen",
  },
  {
    name: "Western Larch",
    scientific_name: "Larix Occidentalis",
    max_height: 192,
    leaf: "Deciduous",
  },
  {
    name: "Western Hemlock",
    scientific_name: "Tsuga Heterophylla",
    max_height: 259,
    leaf: "Evergreen",
  },
  {
    name: "Sitka Spruce",
    scientific_name: "Picea Sitchensis",
    max_height: 314,
    leaf: "Evergreen",
  },
  {
    name: "Douglas Fir",
    scientific_name: "Pseudotsuga Menziesii",
    max_height: 326,
    leaf: "Evergreen",
  },
  {
    name: "Western Juniper",
    scientific_name: "Juniperus Occidentalis",
    max_height: 86,
    leaf: "Evergreen",
  },
  {
    name: "Western Redcedar",
    scientific_name: "Thuja Plicata",
    max_height: 277,
    leaf: "Evergreen",
  },
  {
    name: "Red Alder",
    scientific_name: "Alnus Rubra",
    max_height: 136,
    leaf: "Deciduous",
  },
  {
    name: "Oregon White Oak",
    scientific_name: "Quercus Garryana",
    max_height: 90,
    leaf: "Deciduous",
  },
  {
    name: "Quaking Aspen",
    scientific_name: "Populus Tremuloides",
    max_height: 109,
    leaf: "Deciduous",
  },
  {
    name: "Black Cottonwood",
    scientific_name: "Populus Trichocarpa",
    max_height: 188,
    leaf: "Deciduous",
  },
  {
    name: "Oregon Crab Apple",
    scientific_name: "Malus Fusca",
    max_height: 79,
    leaf: "Deciduous",
  },
  {
    name: "Bigleaf Maple",
    scientific_name: "Acer Macrophyllum",
    max_height: 158,
    leaf: "Deciduous",
  },
  {
    name: "Pacific Dogwood",
    scientific_name: "Cornus Nuttallii",
    max_height: 100,
    leaf: "Deciduous",
  },
  {
    name: "Pacific Madrone",
    scientific_name: "Arbutus Menziesii",
    max_height: 131,
    leaf: "Evergreen",
  },
  {
    name: "Oregon Ash",
    scientific_name: "Fraxinus Latifolia",
    max_height: 111,
    leaf: "Deciduous",
  },
  {
    name: "Western White Pine",
    scientific_name: "Pinus Monticola",
    max_height: 225,
    leaf: "Evergreen",
  },
  {
    name: "Lodgepole Pine",
    scientific_name: "Pinus Contorta var. Latifolia",
    max_height: 150,
    leaf: "Evergreen",
  },
  {
    name: "Noble Fir",
    scientific_name: "Abies Procera",
    max_height: 295,
    leaf: "Evergreen",
  },
  {
    name: "Grand Fir",
    scientific_name: "Abies Grandis",
    max_height: 267,
    leaf: "Evergreen",
  },
  {
    name: "Pacific Silver Fir",
    scientific_name: "Abies Amabilis",
    max_height: 245,
    leaf: "Evergreen",
  },
  {
    name: "Port Orford-Cedar",
    scientific_name: "Chamaecyparis Lawsoniana",
    max_height: 224,
    leaf: "Evergreen",
  },
  {
    name: "Coast Redwood",
    scientific_name: "Sequoia Sempervirens",
    max_height: 379,
    leaf: "Evergreen",
  },
  {
    name: "Vine Maple",
    scientific_name: "Acer Circinatum",
    max_height: 40,
    leaf: "Deciduous",
  },
  {
    name: "Incense-Cedar",
    scientific_name: "Calocedrus Decurrens",
    max_height: 229,
    leaf: "Evergreen",
  },
  {
    name: "Pacific Yew",
    scientific_name: "Taxus  Brevifolia",
    max_height: 75,
    leaf: "Evergreen",
  },
  {
    name: "Oregon Myrtle",
    scientific_name: "Umbellularia Californica",
    max_height: 150,
    leaf: "Evergreen",
  },
];
